%YAML:1.0

# ----- 标定板参数 -----
pattern_cols: 10
pattern_rows: 7
center_distance_mm: 40

R_gimbal2imubody: [1, 0, 0, 0, 1, 0,  0, 0, 1]

# ----- 关键参数2: 相机内参 (填你算出来的) -----
camera_matrix: [3675.6262082469548, 0, 1518.9326665239796, 0, 3673.4179037120011, 1025.3788910396063, 0, 0, 1]
distort_coeffs: [-0.043323339661623529, 0.17515359531109839, 0.00028673731415439056, -0.0013174138640650729, 0]

# ----- 相机驱动参数 -----
camera_name: "hikrobot"
exposure_ms: 3
gain: 20.0
vid_pid: "2bdf:0001"

# ----- 标定采集时的通信设置 -----
com_port: "/dev/gimbal"  #<-- 如果需要采集，确保这里有串口设置make