# ----- 标定板参数 -----
pattern_cols: 10
pattern_rows: 7
center_distance_mm: 20.0

# configs/sentry.yaml & configs/calibration.yaml
R_gimbal2imubody: [0, -1, 0, 1, 0, 0, 0, 0, 1]
# ----- 相机驱动参数 -----
camera_name: "hikrobot"
exposure_ms: 10.0
gain: 22.0
vid_pid: "2bdf:0001"

# 重投影误差: 0.4467px
camera_matrix: [2415.275935077223, 0, 1511.7419207254848, 0, 2417.8913730145359, 1010.3691584064802, 0, 0, 1]
distort_coeffs: [-0.12387336328863864, 0.15376927802480861, -0.00078502615880854225, -0.0013286053680127863, 0]

# 相机同理想情况的偏角: yaw0.83 pitch0.18 roll0.06 degree
R_camera2gimbal: [-0.014417320588344884, 0.0031523374968004357, 0.9998910958876267, -0.9998954802824036, 0.0010360318388304979, -0.014420650084179136, -0.0010813777666912735, -0.99999449468801338, 0.0031370712122154032]
t_camera2gimbal: [0.10071502258862274, -0.0036648749817638909, 0.07134309306129541]

# ----- 标定采集时的通信设置 -----
com_port: "/dev/gimbal"  #<-- 如果需要采集，确保这里有串口设置make