# enemy_color: "red"
enemy_color: "blue"


#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false
use_roi: true

#####-----USB相机参数-----#####
image_width: 1440
image_height: 1080
fov_h: 57.7 #87.7
fov_v: 56.7 
new_fov_h: 27 #67
new_fov_v: 40.9
usb_frame_rate: 30
usb_exposure: 500 #1-80000______250
usb_gamma: 160
usb_gain: 10 #0-96

#####-----工业相机参数-----#####
camera_name: "hikrobot"
exposure_ms: 1.2
gain: 18.0
vid_pid: "2bdf:0001"

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 25
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: -0.8 # degree -2.5
pitch_offset: -1  # degree 2
comming_angle: 60 # degree
leaving_angle: 20 # degree
left_yaw_offset: -1
right_yaw_offset: -0.6
decision_speed: 10 # rad/s
high_speed_delay_time: 0.026 # s
low_speed_delay_time: 0.010 # s

#####-----shooter参数-----#####
first_tolerance: 5 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 3 #距离判断阈值
auto_fire: false # 是否由自瞄控制射击

#####-----decider参数-----#####
mode: 1

#####-----工业相机标定参数-----#####
R_gimbal2imubody: [0, 1, 0, -1, 0, 0, 0, 0, 1]

# 重投影误差: 0.4467px
camera_matrix: [2415.275935077223, 0, 1511.7419207254848, 0, 2417.8913730145359, 1010.3691584064802, 0, 0, 1]
distort_coeffs: [-0.12387336328863864, 0.15376927802480861, -0.00078502615880854225, -0.0013286053680127863, 0]

# 相机同理想情况的偏角: yaw0.46 pitch0.61 roll-1.53 degree
R_camera2gimbal: [-0.0083195760046954614, 0.010498791137270739, 0.99991027599468041, -0.99960756138647755, -0.026835747568381807, -0.0080352891314148939, 0.026748978935305992, -0.99958472279097077, 0.010717933047771133]
t_camera2gimbal: [0.094969301833534511, 0.095006290298006682, 0.050987066291756609]

#####-----gimbal参数-----#####
com_port: "/dev/gimbal"
